

export default function Home() {
 
  return (
    <main className="flex  flex-col items-center justify-between p-24">
      <div>
        <h3>this is home page</h3>
      </div>
    </main>
  );
}
export const metadata = {
  title: "next-hero  | home",
  description: "Generated by create next app",
};