import { Headland_One } from "next/font/google";

const headland = Headland_One({weight: ["400"], subsets:["latin"]})


//  get time 
const getTime = async ( )=>{
  // const res = await fetch('http://localhost:3000/time', {cache: "no-store"});
  const res = await fetch('http://localhost:3000/time', {next: {revalidate: 5}});
  const date =await res.json()
  // console.log(date.currentTime);
  return date.currentTime;
}

export default async function  Home () {
      const presentTime=await getTime()
  return (
    <main className={`flex  flex-col items-center justify-between p-24 ${headland.className}`}>
      <div>
        <h3>this is home page</h3>
        <h3 className="text-green-500 text-3xl font-bold">time: {presentTime}</h3>
        <p>welcome to my next milestone ....... ❤︎</p>
        <p className="text-green-600"> I'm Nayeem,I am a Frontend Developer.I'm a dedicated Frontend
          Developer driven by a passion for creating visually stunning and
          user-friendly web interfaces. My expertise spans HTML, CSS,
          JavaScript, React.js, Node.js, Express.js, Firebase, MongoDB, and
          Tailwind CSS. With a strong focus on design and an ongoing commitment
          to enhancing my skills, I strive to deliver seamless and engaging user
          experiences. I have been involved in web development for several days.
          I am still learning. I have also done several projects. Still doing
          the project. My dream is to become </p>
        
      </div>
    </main>
  );
}


export const metadata = {
  title: "next-hero  | home",
  description: "Generated by create next app",
};